# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: get data and Update DB

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install packages
      run: |
        npm install
    - name: Fetch latest data
      run: |
        npm run getData https://ourairports.com/data/airports.csv airports.csv
    - name: parse latest data
      run: |
        npm run parseData airports.csv
    - name: Commit
      run: |
        git config --local user.email "github-actions[bot]@noreplay.com"
        git config --local user.name "github-actions[bot]"
        git commit -m ":calendar: get data" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
      
